spring:
  application:
    name: "price-comparator-market"
  datasource:
    driver-class-name: org.h2.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"